const productData = [
  // {
  //     name:"",
  //     authors:[""],
  //     covers: [""],
  //     synopsis:"",
  //     formats:[
  //         {type: "", price: 0, discount: 0, stock: 0},
  //         {type: "", price: 0, discount: 0, stock: 0},
  //         {type: "", price: 0, discount: 0, stock: 0},
  //     ],
  //     pages: 0,
  //     language: "",
  //     publishDate: "",
  //     publisher: "",
  //     isbn10: "",
  //     isbn13: "",
  //     weight: "",
  //     dimensions: "",
  //     genres: [""]
  // },
  {
    name: "Harry Potter and the Philosopher's Stone",
    authors: ["J.K. Rowling"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/51ifu1aebKL.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/51kdIBI0MlL.jpg",
    ],
    synopsis:
      "Escape to Hogwarts with the unmissable series that has sparked a lifelong reading journey for children and families all over the world. The magic starts here.<br/>Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. The magic starts here!<br/>These editions of the classic and internationally bestselling Harry Potter series feature thrilling jacket artwork by award-winning illustrator Jonny Duddle. They are the perfect starting point for anyone who's ready to lose themselves in the greatest children's story of all time.",
    formats: [
      { type: "paperback", price: 499.0, discount: 47, stock: 10 },
      { type: "hardcover", price: 1553, discount: 22, stock: 10 },
      { type: "ebook", price: 499, discount: 78, stock: 100 },
    ],
    pages: 352,
    language: "English",
    publishDate: "2014-09-03",
    publisher: "Bloomsbury Children's Books",
    isbn10: "9781408855652",
    isbn13: "978-1408855652",
    weight: "275g",
    dimensions: "12.9 x 2.3 x 19.7 cm",
    genres: ["Fantasy", "Fiction", "YA"],
  },
  {
    name: "Eloquent JavaScript, 3rd Edition: A Modern Introduction to Programming",
    authors: ["Marjin Haverbeke"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/51InjRPaF7L.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91MPjkVOE3L.jpg",
    ],
    synopsis:
      "JavaScript lies at the heart of almost every modern web application, from social apps like Twitter to browser-based game frameworks like Phaser and Babylon. Though simple for beginners to pick up and play with, JavaScript is a flexible, complex language that you can use to build full-scale applications.<br/>This much anticipated and thoroughly revised third edition of Eloquent JavaScript dives deep into the JavaScript language to show you how to write beautiful, effective code. It has been updated to reflect the current state of Java¬Script and web browsers and includes brand-new material on features like class notation, arrow functions, iterators, async functions, template strings, and block scope. A host of new exercises have also been added to test your skills and keep you on track.<br/>As with previous editions, Haverbeke continues to teach through extensive examples and immerses you in code from the start, while exercises and full-chapter projects give you hands-on experience with writing your own programs. You start by learning the basic structure of the JavaScript language as well as control structures, functions, and data structures to help you write basic programs. Then you'll learn about error handling and bug fixing, modularity, and asynchronous programming before moving on to web browsers and how JavaScript is used to program them. As you build projects such as an artificial life simulation, a simple programming language, and a paint program, you'll learn how to:<br/>- Understand the essential elements of programming, including syntax, control, and data<br/>- Organize and clarify your code with object-oriented and functional programming techniques<br/>- Script the browser and make basic web applications<br/>- Use the DOM effectively to interact with browsers<br/>- Harness Node.js to build servers and utilities<br/>Isn't it time you became fluent in the language of the Web?<br/>* All source code is available online in an inter¬active sandbox, where you can edit the code, run it, and see its output instantly.",
    formats: [
      { type: "paperback", price: 2699.0, discount: 26, stock: 10 },
      { type: "ebook", price: 2485.0, discount: 34, stock: 100 },
    ],
    pages: 472,
    language: "English",
    publishDate: "2018-12-04",
    publisher: "No Starch Press",
    isbn10: "1593279507",
    isbn13: "978-1593279509",
    weight: "907g",
    dimensions: "17.93 x 2.87 x 23.5 cm",
    genres: ["Textbook"],
  },
  {
    name: "The Way of Kings",
    authors: ["Brandon Sanderson"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/51ttJEFwlNL.jpg",
    ],
    synopsis:
      "From #1 New York Times bestselling author Brandon Sanderson, The Way of Kings, Book One of the Stormlight Archive begins an incredible new saga of epic proportion.<br/>Roshar is a world of stone and storms. Uncanny tempests of incredible power sweep across the rocky terrain so frequently that they have shaped ecology and civilization alike. Animals hide in shells, trees pull in branches, and grass retracts into the soilless ground. Cities are built only where the topography offers shelter.<br/>It has been centuries since the fall of the ten consecrated orders known as the Knights Radiant, but their Shardblades and Shardplate remain: mystical swords and suits of armor that transform ordinary men into near-invincible warriors. Men trade kingdoms for Shardblades. Wars were fought for them, and won by them.<br/>One such war rages on a ruined landscape called the Shattered Plains. There, Kaladin, who traded his medical apprenticeship for a spear to protect his little brother, has been reduced to slavery. In a war that makes no sense, where ten armies fight separately against a single foe, he struggles to save his men and to fathom the leaders who consider them expendable.<br/>Brightlord Dalinar Kholin commands one of those other armies. Like his brother, the late king, he is fascinated by an ancient text called The Way of Kings. Troubled by over-powering visions of ancient times and the Knights Radiant, he has begun to doubt his own sanity.<br/>Across the ocean, an untried young woman named Shallan seeks to train under an eminent scholar and notorious heretic, Dalinar's niece, Jasnah. Though she genuinely loves learning, Shallan's motives are less than pure. As she plans a daring theft, her research for Jasnah hints at secrets of the Knights Radiant and the true cause of the war.<br/>The result of over ten years of planning, writing, and world-building, The Way of Kings is but the opening movement of the Stormlight Archive, a bold masterpiece in the making.<br/>Speak again the ancient oaths:<br/>Life before death. Strength before weakness. Journey before Destination. and return to men the Shards they once bore. The Knights Radiant must stand again.",
    formats: [
      { type: "paperback", price: 707.0, discount: 0, stock: 10 },
      { type: "hardcover", price: 3039.0, discount: 47, stock: 10 },
      { type: "ebook", price: 599.0, discount: 68, stock: 100 },
    ],
    pages: 1280,
    language: "English",
    publishDate: "2011-05-24",
    publisher: "Tor Fantasy",
    isbn10: "0765365278",
    isbn13: "0765365279",
    weight: "567g",
    dimensions: "10.72 x 5.08 x 17.83 cm",
    genres: ["Fantasy", "Fiction"],
  },

  {
    name: "Crooked Kingdom",
    authors: ["Leigh Bardugo"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/51vfMAnQCrS.jpg",
    ],
    synopsis:
      "The stunning sequel to SIX OF CROWS, this is GAME OF THRONES meets OCEAN'S ELEVEN in a fantasy epic from the number 1 NEW YORK TIMES bestselling author Leigh Bardugo.<br/>Welcome to the world of the Grisha.<br/>Kaz Brekker and his crew of deadly outcasts have just pulled off a heist so daring even they didn't think they'd survive. But instead of divvying up a fat reward, they're right back to fighting for their lives.<br/>Double-crossed and badly weakened, the crew is low on resources, allies, and hope. As powerful forces from around the world descend on Ketterdam to root out the secrets of the dangerous drug known as jurda parem, old rivals and new enemies emerge to challenge Kaz's cunning and test the team's fragile loyalties.<br/>A war will be waged on the city's dark and twisting streets - a battle for revenge and redemption that will decide the fate of the Grisha world.<br/>As gripping, sweeping and memorable as the Grisha trilogy - SHADOW AND BONE, SIEGE AND STORM and RUIN AND RISING - this novel is perfect for fans of Sarah J. Maas, Laini Taylor, Kristin Cashore and GAME OF THRONES.<br/>",
    formats: [
      { type: "paperback", price: 499, discount: 13, stock: 10 },
      { type: "hardcover", price: 1729, discount: 28, stock: 10 },
      { type: "ebook", price: 499, discount: 57, stock: 100 },
    ],
    pages: 561,
    language: "English",
    publishDate: "2016-09-27",
    publisher: "Orion Children's Books",
    isbn10: "9781780622316",
    isbn13: "978-1780622316",
    weight: "440 g",
    dimensions: "12.8 x 4 x 19.6 cm",
    genres: ["Fantasy", "Fiction", "YA"],
  },
  {
    name: "The Maze Runner: 1",
    authors: ["James Dashner"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/51jtcz5KzTS.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/7104QcYztxL.jpg",
    ],
    synopsis:
      "The Maze runner is the story of Thomas, who finds himself in a Glade, a place surrounded by an ever-changing maze, which has part-mechanic part mucus monsters called Grievers. He is at a complete loss of memory and is stuck therein with some 60 other boys called ‘Gladers.’ Runners are those who try and find a way out of the maze. He finds that sting of a Griever can recall old memories, but it is a terrifying process. In his journey of time, he makes friends with various inmates.<br/>As the story proceeds, we see that Thomas increasingly desires to join the Runners in their pursuit and one day he does find such a chance. Making his own capabilities realised, he earns himself the title of ‘keeper of the runners’. In his quest for the way out, Thomas finds a transparent hole which he refers to as the Griever Hole, which renders the glade unprotected from the Grievers. With the help of his friends, he finds the code to way out. The desperation from curiosity makes him decide to get attacked by Grievers, bringing him closer to the solution of the maze.<br/>Will this code be their ticket out of the maze, will Thomas be able to vend of all the Grievers, while he approaches the Hole, what has brought him to this Glade and what is his purpose of being there, in that place are the questions that make the theme of the book The Maze runner, published by Chicken House as first edition in 2011.",
    formats: [
      { type: "paperback", price: 350, discount: 43, stock: 10 },
      { type: "hardcover", price: 1370, discount: 0, stock: 10 },
    ],
    pages: 384,
    language: "English",
    publishDate: "2011-08-04",
    publisher: "Chicken House",
    isbn10: "9781908435132",
    isbn13: "978-1908435132",
    weight: "290 g",
    dimensions: "13.2 x 2.6 x 19.7 cm",
    genres: ["Fantasy", "Fiction"],
  },
  {
    name: "Not A Penny More, Not A Penny Less",
    authors: ["Jeffrey Archer"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/51-obW1EA2L.jpg",
    ],
    synopsis:
      "Jeffrey Archer's first novel, Not a Penny More, Not a Penny Less, is page-turning tale of fraud, revenge and determination as four men stop at nothing to get back what was stolen from them.<br/>One million dollars – that's what Harvey Metcalfe, lifelong king of shady deals, has pulled off with empty promises of an oil bonanza and instant riches. Overnight, four men – the heir to an earldom, a Harley Street doctor, a Bond Street art dealer and an Oxford don – find themselves penniless. But this time Harvey has swindled the wrong men. They band together and shadow him from the casinos of Monte Carlo to the high-stakes windows at Ascot and the hallowed lawns of Oxford. Their plan is simple: to sting the crook for exactly what they lost – not a penny more, not a penny less.",
    formats: [
      { type: "paperback", price: 399, discount: 29, stock: 10 },
      { type: "hardcover", price: 1335, discount: 0, stock: 10 },
      { type: "ebook", price: 375, discount: 29, stock: 100 },
    ],
    pages: 353,
    language: "English",
    publishDate: "2012-09-13",
    publisher: "Pan",
    isbn10: "9781447218227",
    isbn13: "978-1447218227",
    weight: "240 g",
    dimensions: "12.9 x 2.4 x 19.7 cm",
    genres: ["Thriller", "Mystery"],
  },
  {
    name: "A Game of Thrones: A Song of Ice and Fire",
    authors: ["George R.R. Martin"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/51DtMBkJTRL.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/91piHni6HqL.jpg",
    ],
    synopsis:
      "Full of drama and adventure, rage and lust, mystery and romance, George R.R. Martin’s 'Game of Thrones: Song of Fire and Ice’ (Book I) is regarded as one of the most intriguing and greatest epic of the modern era. Set in 12, 000BC, the seasons in this epic change after decades and bring with them mystery and death. The epic opens with the winter season fast approaching; though the human are protected and safe within the protective ice Wall of the kingdom, winter has arose the deadly forces that are continuously threatening the identity of the mortal power.<br/>In the first book replete with lust, rage, anger, betrayal and terror, two families take the central position: the Lannisters and the Starks. Will the good prevail over the worse? Or, is the scenario going to be much worse than ever? And, who is this new character Daenerys Targaryen? The adventurous tale of magic, power and supernatural forces promise to sway the readers off their feet till the end.<br/>Published in 1996, the novel has received much critical acclaims, including the Ignotus Award, the Hugo Award and the Locus Award. It was also adapted into a famous TV-series by HBO.",
    formats: [{ type: "paperback", price: 599, discount: 46, stock: 10 }],
    pages: 846,
    language: "English",
    publishDate: "2011-03-31",
    publisher: "Voyager",
    isbn10: "9780007428540",
    isbn13: "978-0007428540",
    weight: "550 g",
    dimensions: "4.32 x 12.95 x 19.56 cm",
    genres: ["Fantasy", "Fiction"],
  },
  {
    name: "The Name of the Wind",
    authors: ["Patrick Rothfuss"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/51-TOtX11mL.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/711U8DlxOXL.jpg",
    ],
    synopsis:
      "'I have stolen princesses back from sleeping barrow kings. I burned down the town of Trebon. I have spent the night with Felurian and left with both my sanity and my life. I was expelled from the University at a younger age than most people are allowed in. I tread paths by moonlight that others fear to speak of during day. I have talked to Gods, loved women, and written songs that make the minstrels weep.<br/>My name is Kvothe.You may have heard of me'<br/>So begins the tale of Kvothe - currently known as Kote, the unassuming innkeepter - from his childhood in a troupe of traveling players, through his years spent as a near-feral orphan in a crime-riddled city, to his daringly brazen yet successful bid to enter a difficult and dangerous school of magic. In these pages you will come to know Kvothe the notorious magician, the accomplished thief, the masterful musician, the dragon-slayer, the legend-hunter, the lover, the thief and the infamous assassin.",
    formats: [
      { type: "paperback", price: 499, discount: 17, stock: 10 },
      { type: "hardcover", price: 1050, discount: 12, stock: 10 },
    ],
    pages: 672,
    language: "English",
    publishDate: "2008-06-12",
    publisher: "Gollancz",
    isbn10: "0756404746",
    isbn13: "978-0575081406",
    weight: "476 g",
    dimensions: "19.8 x 4 x 13.1 cm",
    genres: ["Fantasy", "Fiction"],
  },
  {
    name: "Think and Grow Rich",
    authors: ["Napolean Hill"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/41+eK8zBwQL.jpg",
    ],
    synopsis:
      "Think and Grow Rich has earned itself The reputation of being considered a textbook for actionable techniques that can help one get better at doing anything, not just by rich and wealthy, but also by people doing wonderful work in their respective fields. There are hundreds and thousands of successful people in the world who can vouch for the contents of this book. At the time of authors death, about 20 million copies had already been sold. Numerous revisions have been made in the book, from time to time, to make the book more readable and comprehensible to the readers. The book details out the most fundamental questions that once bothered the author, Napoleon Hill. The author once set out on a personal quest to find out what really made some people so successful. Why is it that some people manage to remain healthy, happy and financially independent, all at the same time? Why, after all, do some end up being called as lucky? The answers, no wonder, had to be no less than revelations. For more than a decade, the author interviewed some of the wealthiest and most successful people in the world. It was based on what author learnt in the process from all these people, when asked about how they achieved not just great riches but also personal wellbeing. The author formulated hundreds and thousands of answers, into concise principles which when acted upon, many claim, can help one achieve unprecedented success. The author has in many places narrated short stories and examples that help explain the concept at hand in an engaging manner. Think and Grow Rich teaches not just concepts but also methods. It is not a book that a reader can use for one time consumption. The book, even author recommends, has to be read one br>Chapter at a time and in sequence. Several readers and even some motivational speakers claim to have been reading this book over and over again, few pages at a time, for a long time now. Till date, it remains the number one self help book in the world, as far as sales are concerned! About author: an American journalist, lecturer and author, Napoleon Hill is one of the earliest producers of 'personal-success literature’. as an author of self-help books, Hill has always abided by and promoted principle of intense and burning passion being the sole key to achieve success. Hill has authored numerous books among which think and Grow Rich has been his most well-known works and had sold over 20 million copies back in the 1930s.",
    formats: [{ type: "paperback", price: 175, discount: 25, stock: 10 }],
    pages: 250,
    language: "English",
    publishDate: "2014-01-01",
    publisher: "Amazing Reads",
    isbn10: "8192910911",
    isbn13: "978-8192910918",
    weight: "310 g",
    dimensions: "13 x 1.5 x 20 cm",
    genres: ["Business & Economics"],
  },
  {
    name: "Deep Work: Rules for Focused Success in a Distracted World",
    authors: ["Cal Newport"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/418Mmq-lMLL.jpg",
    ],
    synopsis:
      "Cal Newport discusses in his new book, Deep Work: Rules For Focused Success In A Distracted World, about how professionals of today have started valuing quantity over quality; and how this has turned young professionals of today into puppets who try to indulge in extensive multitasking, dealing with multiple emails and projects. This prevents them from doing 'deep work'; which is focused work free from all other distractions. This also means that the professionals of today should sort out their priorities.<br/>Newport uses principles of psychology and neuroscience to enhance his points. He elaborates how to improve a person's cognitive abilities and how employers should encourage workers to not take shortcuts for completing projects. He claims that the best way to break away from the corporate race is to take a break from technology and social media and use some alone-time to rewind and introspect. Newport enforces the beliefs of a non-technophile to deliver work that is productive and efficiently delivered.",
    formats: [
      { type: "paperback", price: 399, discount: 32, stock: 10 },
      { type: "ebook", price: 399, discount: 70, stock: 100 },
    ],
    pages: 304,
    language: "English",
    publishDate: "2016-02-12",
    publisher: "Little, Brown Book Group",
    isbn10: "9780349413686",
    isbn13: "978-0349413686",
    weight: "220 g",
    dimensions: "20 x 14 x 4 cm",
    genres: ["Business & Economics"],
  },
  {
    name: "The Psychology of Money",
    authors: ["Morgan Housel"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/41cWqh0OeQL.jpg",
    ],
    synopsis:
      "Timeless lessons on wealth, greed, and happiness doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people. How to manage money, invest it, and make business decisions are typically considered to involve a lot of mathematical calculations, where data and formulae tell us exactly what to do. But in the real world, people don’t make financial decisions on a spreadsheet. They make them at the dinner table, or in a meeting room, where personal history, your unique view of the world, ego, pride, marketing, and odd incentives are scrambled together. In the psychology of money, the author shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life’s most important matters.",
    formats: [
      { type: "paperback", price: 399, discount: 33, stock: 10 },
      { type: "hardcover", price: 2116, discount: 0, stock: 10 },
    ],
    pages: 252,
    language: "English",
    publishDate: "2020-09-01",
    publisher: "Jaico Publishing House",
    isbn10: "9390166268",
    isbn13: "978-9390166268",
    weight: "220 g",
    dimensions: "20 x 14 x 4 cm",
    genres: ["Business & Economics"],
  },
  {
    name: "The Fellowship of the Ring: Book 1 (The Lord of the Rings)",
    authors: ["J.R.R. Tolkien"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/41Q4zhhBHFL.jpg",
    ],
    synopsis:
      "The Fellowship of the Ring is the first of the three volumes that comprise The Lord of the Rings novel. Set in a mythical universe of Middle-earth, this book continues in the same tone as The Hobbit. The Dark Lord, Sauron, is the Lord of the Rings, who is on a mission to reclaim the One Ring and use it to enslave all of Middle-earth.<br/>The Fellowship Of The Ring commences with a birthday party in Hobbiton. Bilbo Baggins, the current possessor of the Ring, turns 111 and bequeaths the ring to his cousin, Frodo Baggins. Several years pass and the wizard Gandalf routinely visits Frodo in Bag End. One spring night, he tells Frodo the truth about the Ring and the story behind it. He informs him that Sauron has risen again and is in search of the Ring. Upon learning this, Frodo departs from the Shire alongside three Hobbit friends: Sam, Merry and Pippin.<br/>Along the way, the four of them are faced with several obstacles and distractions, including Ringwraiths, who are the servants of Sauron, a malevolent willow tree and an evil tomb ghost. The group befriends wandering Elves on the way and set upon their path across Middle-earth to the Cracks of Doom, intending to destroy the Ring and foil the Dark Lords plan.<br/>",
    formats: [{ type: "paperback", price: 499, discount: 31, stock: 10 }],
    pages: 576,
    language: "English",
    publishDate: "2012-11-01",
    publisher: "Harpercollins",
    isbn10: "0007488300",
    isbn13: "978-0007488308",
    weight: "310 g",
    dimensions: "17.53 x 10.92 x 4.06 cm",
    genres: ["Fantasy", "Fiction"],
  },
  {
    name: "Murder on the Orient Express",
    authors: ["Agatha Christie"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/51UA4cTPAhL.jpg",
    ],
    synopsis:
      "Just after midnight, a snowdrift stops the Orient Express in its tracks. The luxurious train is surprisingly full for the time of the year, but by the morning it is one passenger fewer. An American tycoon lies dead in his compartment, stabbed a dozen times, his door locked from the inside.<br/>Isolated and with a killer in their midst, detective Hercule Poirot must identify the murderer – in case he or she decides to strike again.",
    formats: [
      { type: "paperback", price: 299, discount: 27, stock: 10 },
      { type: "hardcover", price: 399, discount: 13, stock: 10 },
    ],
    pages: 288,
    language: "English",
    publishDate: "2017-10-05",
    publisher: "Harper Collins",
    isbn10: "9780007527502",
    isbn13: "9780007527502",
    weight: "200 g",
    dimensions: "12.9 x 1.8 x 19.8 cm",
    genres: ["Mystery", "Fiction"],
  },
  {
    name: "Gone Girl",
    authors: ["Gillian Flynn"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/41aEQgTFPoL.jpg",
    ],
    synopsis:
      "Gone Girl is a novel written by author Gillian Flynn. It is written as a contemporary thriller novel and is first published in June 2012. The novel's core mystery stems from an uncertainty about the protagonist, Nick Dunne. Whether Nick killed his wife, Amy Dunne, is the suspense the novel is built up on. The novel is well received throughout the United States and other English-speaking nations.<br/>Gone Girl centers its story about Nick and Amy Dunne's strained marriage relationship. Nick used to work as a journalist, but loses his job. With his broke financial status, Nick decides to relocate from New York City to his smaller home town, North Carthage. In an attempt of recovering from his financial deprivations, Nick opens a bar using the money from his wife. Nick runs the bar along with his twin sister Margo, providing a decent living for his family. But, as they days go by, his marriage with Amy is falling apart slowly. Amy resents her new life.<br/>On a summer morning in Missouri, when Nick and Amy are celebrating their fifth wedding anniversary along with their relatives and acquaintances, Amy goes missing. Police's eyes turn towards Nick as an act of suspicion, since Nick used Amy's money for his business and their relationship is strained. As the police delve into the investigation, different shades of stories come out from Nick's and Amy's sides. The suspense of the book is carried until the actual information is demystified. The edition is published in paperback, on 8th November, 2012.",
    formats: [{ type: "paperback", price: 399, discount: 33, stock: 10 }],
    pages: 480,
    language: "English",
    publishDate: "2012-11-08",
    publisher: "Orion Publishing Group",
    isbn10: "B01KAGF6XY",
    isbn13: "B01KAGF6XY",
    weight: "250 g",
    dimensions: "11.6 x 3.2 x 17.7 cm",
    genres: ["Mystery", "Thriller"],
  },
  // remove below book
  {
    name: "The Girl With the Dragon Tattoo",
    authors: ["Stieg Larsson"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/51lmb+j6L4L.jpg",
    ],
    synopsis:
      "Stieg Larsson's #1 bestselling mystery featuring Lisbeth Salander is now a major motion picture directed by David Fincher, starring Daniel Craig and Rooney Mara, from Columbia Pictures/Sony. In theaters December 2011. The first volume in the Millennium Trilogy, and an international publishing sensation, 'The Girl with the Dragon' Tattoo combines murder mystery, family saga, love story, and financial intrigue into one satisfyingly complex and entertainingly atmospheric novel.",
    formats: [{ type: "paperback", price: 1000, discount: 0, stock: 10 }],
    pages: 644,
    language: "English",
    publishDate: "2011-11-22",
    publisher: "Turtleback Books",
    isbn10: "0606264728",
    isbn13: "978-0606264723",
    weight: "363 g",
    dimensions: "10.41 x 4.32 x 18.54 cm",
    genres: ["Mystery", "Thriller"],
  },
  {
    name: "The Fault in our Stars",
    authors: ["John Green"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/51r27MDeQQL.jpg",
    ],
    synopsis:
      "The Fault in our Stars is a book for everyone, be it people in their old age, or teens studying in school, this book is an ideal feel good and emotional novel for all. Written by John Green and published by Penguin UK, in the year 2013, this book has gone on to become a major seller in all parts of the world. It has sold more than ten million copies worldwide.<br/>The book is about two teenagers, Hazel Grace Lancaster and Augustus Waters, who are also the protagonists and follows their lives when they are diagnosed with terminal cancer. Their lives change completely post diagnosis. Hazel meets Augustus for the very first time at a, support centre for cancer patients and survivors, which she had started to attend. Augustus is there for a remission. This is when they meet each other and their lives see some light again and they feel alive and better. This is a book that has it all be it love, emotion, drama, humour, pain, fear and even death.<br/>As the book progresses, the readers are unwittingly brought into the lives of the characters and start feeling and thinking about them as one of their own. The various turns that Hazel and Augustus go through, the tragic moments, the funny moments and the times when the readers are left teary eyed, is what makes this book worth a read. The readers gain an insight into the lives of people who are diagnosed by terminal cancer, the struggles they go through, their daily lives and how cancer disrupts the lives of the other people involved as well. However, the story also leaves a message of courage, true happiness and how to live life. This book through its protagonists try to tell that one should not feel pity for themselves, rather embrace life or what’s precious is left of it. It touches the chords of the readers’ hearts through its emotional appeal.",
    formats: [
      { type: "paperback", price: 399, discount: 41, stock: 10 },
      { type: "hardcover", price: 1000, discount: 0, stock: 10 },
    ],
    pages: 316,
    language: "English",
    publishDate: "2013-01-03",
    publisher: "Penguin",
    isbn10: "0141345659",
    isbn13: "978-0141345659",
    weight: "237 g",
    dimensions: "12.8 x 2.2 x 19.7 cm",
    genres: ["Romance", "Fiction", "YA"],
  },
  {
    name: "Twilight: Book 1 (Twilight Saga)",
    authors: ["Stephenie Meyer"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/41+mG-652WL.jpg",
    ],
    synopsis:
      "When 17 year old Isabella Swan moves to Forks, Washington to live with her father she expects that her new life will be as dull as the town.<br/>But in spite of her awkward manner and low expectations, she finds that her new classmates are drawn to this pale, dark-haired new girl in town. But not, it seems, the Cullen family. These five adopted brothers and sisters obviously prefer their own company and will make no exception for Bella.<br/>Bella is convinced that Edward Cullen in particular hates her, but she feels a strange attraction to him, although his hostility makes her feel almost physically ill. He seems determined to push her away - until, that is, he saves her life from an out of control car.<br/>Bella will soon discover that there is a very good reason for Edward's coldness. He, and his family, are vampires - and he knows how dangerous it is for others to get too close.",
    formats: [{ type: "paperback", price: 499, discount: 30, stock: 10 }],
    pages: 464,
    language: "English",
    publishDate: "2007-03-22",
    publisher: "Atom",
    isbn10: "9781904233657",
    isbn13: "9781904233657",
    weight: "320 g",
    dimensions: "12.9 x 3 x 19.7 cm",
    genres: ["Fantasy", "Fiction", "Romance", "YA"],
  },
  {
    name: "The Alchemist",
    authors: ["Paulo Coelho"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/410llGwMZGL.jpg",
    ],
    synopsis:
      "Paulo Coelho's enchanting novel has inspired a devoted following around the world. This story, dazzling in its powerful simplicity and inspiring wisdom, is about an Andalusian shepherd boy named Santiago who travels from his homeland in Spain to the Egyptian desert in search of a treasure buried in the Pyramids. Along the way he meets a Gypsy woman, a man who calls himself",
    formats: [{ type: "paperback", price: 350, discount: 25, stock: 10 }],
    pages: 172,
    language: "English",
    publishDate: "2005-10-17",
    publisher: "Harper",
    isbn10: "9788172234980",
    isbn13: "9788172234980",
    weight: "80 g",
    dimensions: "12.9 x 1.5 x 19.8 cm",
    genres: ["Fiction"],
  },
  {
    name: "The Hunger Games: 1",
    authors: ["Suzanne Collins"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/41P6E4OSRoL.jpg",
    ],
    synopsis:
      "The first book in the ground-breaking Hunger Games trilogy.<br/>Set in a dark vision of the near future, a terrifying reality TV show is taking place.<br/>Twelve boys and twelve girls are forced to appear in a live event called The Hunger Games.<br/>There is only one rule: kill or be killed.<br/>When sixteen-year-old Katniss Everdeen steps forward to take her younger sister's place in the games, she sees it as a death sentence.<br/>But Katniss has been close to death before. For her, survival is second nature.",
    formats: [{ type: "paperback", price: 699, discount: 0, stock: 10 }],
    pages: 448,
    language: "English",
    publishDate: "2011-12-01",
    publisher: "Scholastic",
    isbn10: "1407132083",
    isbn13: "978-1407132082",
    weight: "270 g",
    dimensions: "13.6 x 2.9 x 19.8 cm",
    genres: ["Fantasy", "Fiction", "Romance", "YA"],
  },
  {
    name: "JavaScript: The Definitive Guide",
    authors: ["David Flanagan"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/51fOFa903iL.jpg",
    ],
    synopsis:
      "JavaScript is the programming language of the web and is used by more software developers today than any other programming language. For nearly 25 years this best seller has been the go-to guide for JavaScript programmers. The seventh edition is fully updated to cover the 2020 version of JavaScript, and new chapters cover classes, modules, iterators, generators, Promises, async/await, and metaprogramming. You’ll find illuminating and engaging example code throughout.<br/>This book is for programmers who want to learn JavaScript and for web developers who want to take their understanding and mastery to the next level. It begins by explaining the JavaScript language itself, in detail, from the bottom up. It then builds on that foundation to cover the web platform and Node.js.",
    formats: [{ type: "paperback", price: 2150, discount: 0, stock: 10 }],
    pages: 708,
    language: "English",
    publishDate: "2020-06-15",
    publisher: "Shroff/O'Reilly",
    isbn10: "9352139968",
    isbn13: "978-9352139965",
    weight: "1 kg 100 g",
    dimensions: "22.9 x 17.8 x 3.3 cm",
    genres: ["Textbook"],
  },
  {
    name: "Brief Answers to the Big Questions",
    authors: ["Stephen Hawking"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/41JU-lDfebL.jpg",
    ],
    synopsis:
      "Is there a God?<br/>How did it all begin?<br/>Can we predict the future?<br/>What is inside a black hole?<br/>Is there other intelligent life in the universe?<br/>Will artificial intelligence outsmart us?<br/>How do we shape the future?<br/>Will we survive on Earth?<br/>Should we colonise space?<br/>Is time travel possible?<br/><br/>Throughout his extraordinary career, Stephen Hawking expanded our understanding of the universe and unravelled some of its greatest mysteries. But even as his theoretical work on black holes, imaginary time and multiple histories took his mind to the furthest reaches of space, Hawking always believed that science could also be used to fix the problems on our planet.<br/><br/>And now, as we face potentially catastrophic changes here on Earth - from climate change to dwindling natural resources to the threat of artificial super-intelligence - Stephen Hawking turns his attention to the most urgent issues for humankind.<br/><br/>Wide-ranging, intellectually stimulating, passionately argued, and infused with his characteristic humour, BRIEF ANSWERS TO THE BIG QUESTIONS, the final book from one of the greatest minds in history, is a personal view on the challenges we face as a human race, and where we, as a planet, are heading next.",
    formats: [{ type: "paperback", price: 650, discount: 36, stock: 10 }],
    pages: 256,
    language: "English",
    publishDate: "2018-10-17",
    publisher: "John Murray",
    isbn10: "1473695988",
    isbn13: "978-1473695986",
    weight: "386 g",
    dimensions: "16.3 x 2.8 x 22.1 cm",
    genres: ["Textbook"],
  },
  {
    name: "The Road to Learn React",
    authors: ["Robin Wieruch"],
    covers: [
      "https://images-na.ssl-images-amazon.com/images/I/41AJiI9AyyL.jpg",
    ],
    synopsis:
      "The road to learn react teaches you the fundamentals of react. You will build a real world application along the way in plain react without complicated tooling. Everything from project setup to deployment on a server will be explained. The book comes with additional referenced reading material and exercises with each br>Chapter after reading the book, you will be able to build your own applications in react. The material is kept up to date by me and the community. In the road to learn react, I want to offer a foundation before you start to dive into the broader react ecosystem. It has less tooling and less external state management, but a lot of information around react. It explains General concepts, patterns and best practices in a real world react application. You will learn to build your own react application. It covers real world features like pagination, client-side caching and interactions like searching and sorting. Additionally you will transition from JavaScript ES5 to JavaScript ES6 along the way. I hope this book captures My enthusiasm for react and JavaScript and helps you to get started.",
    formats: [{ type: "paperback", price: 1793, discount: 0, stock: 10 }],
    pages: 248,
    language: "English",
    publishDate: "2018-01-01",
    publisher: "Zaccheus Entertainment",
    isbn10: "9781720043997",
    isbn13: "978-1720043997",
    weight: "585 g",
    dimensions: "21.59 x 1.42 x 27.94 cm",
    genres: ["Textbook"],
  },
  // {
  //   name: "Alchemist: Hindi Edition",
  //   authors: ["Paulo Coelho"],
  //   covers: [
  //     "https://images-na.ssl-images-amazon.com/images/I/518MJJJCMoL.jpg",
  //   ],
  //   synopsis:
  //     "अल्केमिस्टकी 8.5 करोड़प्रतियोंकीबिक्रीहोचुकीहै।अपनीज़बरदस्तसरलताऔरआत्माकोझकझोरदेनेवालीबुद्धिमत्तासेयुक्तयहसेंटियागोनामकएकएंडालूसियाईगड़रियालड़केकीकहानीहैजोमिस्रकेपिरामिडोंमेंदफ़्नएकख़ज़ानेकीखोजमेंअपनीमातृभूमिस्पेनसेमिस्रकेरेगिस्तानतककासफ़रकरताहै।रास्तेमेंउसकीमुलाक़ातएकजिप्सीऔरतसे, खुदकोराजाकहनेवालेएकव्यक्तिसे, औरएककीमियागरसेहोतीहै।येसभीसेंटियागोकोउसकीखोजकीदिशामेंजानेकासंकेतकरतेहैं।कोईनहींजानताकिवहख़ज़ानाक्याहै, औरसेंटियागोरास्तेमेंआनेवालीरुकावटोंकोपारकरपाएगायानहीं।लेकिनसांसारिकवस्तुओंकीखोजकेतौरपरशुरूहुईयहयात्राअन्तमेंअपनेहीभीतरछिपेख़ज़ानेकीखोजकीयात्रासाबितहोतीहै।सेंटियागोकीयहअत्यन्तचित्ताकर्षक, उत्प्रेरक, औरमानवीयमर्मसेयुक्तकहानीहमारेस्वप्नोंकीरूपान्तरकारीशक्तिऔरअपनेहृदयकीआवाज़सुननेकेमहत्त्वकाशाश्वतप्रमाणहै।‘‘पाओलोकोएलोकीपुस्तकोंसेप्रभावितहोकरलाखोंलोगअपनेजीवनकोनिखारनेकेलिएप्रेरितहुएहैं।’’- दटाइम्स.",
  //   formats: [{ type: "paperback", price: 199, discount: 34, stock: 10 }],
  //   pages: 188,
  //   language: "Hindi",
  //   publishDate: "2020-09-10",
  //   publisher: "Manjul Publishing House",
  //   isbn10: "9390085195",
  //   isbn13: "978-9390085194",
  //   weight: "200 g",
  //   dimensions: "20 x 14 x 4 cm",
  //   genres: ["Fiction"],
  // },
  // {
  //     name:"",
  //     authors:[""],
  //     covers: [""],
  //     synopsis:"",
  //     formats:[
  //         {type: "", price: 0, discount: 0, stock: 0},
  //         {type: "", price: 0, discount: 0, stock: 0},
  //         {type: "", price: 0, discount: 0, stock: 0},
  //     ],
  //     pages: 0,
  //     language: "",
  //     publishDate: "",
  //     publisher: "",
  //     isbn10: "",
  //     isbn13: "",
  //     weight: "",
  //     dimensions: "",
  //     genres: [""]
  // },
  // *--------------------------
  // mystery - girl with the dragon tat, gone girl, murder on the orient express
  // scient fiction  / fantasy - crooked king
];

module.exports = productData;
